version: '2'

services:
  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    build: .
    depends_on:
      - db
    ports:
      - 3001:3001
    volumes:
      - .:/app
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  db:
    image: mongo
    ports:
      - 27017:27017
